### ISSUE TITLE
Error executing process > 'align_mtDNA_MToolBox (1)'; Heteroplasmy data file ('VCF_dict_tmp') not found; No annotation.csv found. Exit

### ISSUE THREAD

**Issue by rhughwhite** [uclahs-cds/pipeline-call-mtSNV#104]
* Full error below.
* Paired tumor-normal **WXS** samples
* Initially running as part of metapipeline-DNA, but also re-run with call-gSNP -> call-mtSNV individually
* F72
* call-mtSNV version 3.0.0
* Using "default" GRCh38 reference files suggested in [metapipeline-DNA template config](https://github.com/uclahs-cds/metapipeline-DNA/blob/main/config/template.config)
* Used python submission script -> /hot/data/unregistered/Robinson-Livingstone-PRAD-IGXR/exome/metapipeline-DNA/troubleshooting/call-mtSNV/run_call-mtSNV.sh
* Log = /hot/data/unregistered/Robinson-Livingstone-PRAD-IGXR/exome/metapipeline-DNA/troubleshooting/call-mtSNV/RLPRIGXR000011_sorted_bed.log
* config = /hot/data/unregistered/Robinson-Livingstone-PRAD-IGXR/exome/metapipeline-DNA/troubleshooting/call-mtSNV/config/RLPRIGXR000011.config
* input = /hot/data/unregistered/Robinson-Livingstone-PRAD-IGXR/exome/metapipeline-DNA/troubleshooting/call-mtSNV/input/RLPRIGXR000011.csv

**Update**
Also tried running with BAMs from align-DNA (no post-processing with call-gSNP) and received the same issue - RLPRIGXR000011_align-DNA.log

**Additional info**
* call-gSNP config = /hot/data/unregistered/Robinson-Livingstone-PRAD-IGXR/exome/metapipeline-DNA/troubleshooting/call-gSNP/config/RLPRIGXR000011_sorted_bed.config
* call-gSNP run with a regions file (bed file) containing regions targeted for sequencing (exome) = /hot/data/unregistered/Robinson-Livingstone-PRAD-IGXR/exome/metapipeline-DNA/exome_regions/S03723314_Covered.GRCh38.sorted.bed
* `samtools flagstats` outputs for call-gSNP BAMs = /hot/data/unregistered/Robinson-Livingstone-PRAD-IGXR/exome/metapipeline-DNA/troubleshooting/call-gSNP/RLPRIGXR000011*samtools_flagstats.txt

> Error executing process > 'align_mtDNA_MToolBox (1)'
> Caused by:
>   Process `align_mtDNA_MToolBox (1)` terminated with an error exit status (1)
> 
> 
> Command executed:
> 
>   printf "input_type='bam'
>   ref='RSRS'
>   input_path=extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F.bam
>   gsnapdb=/src/gmapdb/
>   fasta_path=/src/genome_fasta/
>   " > config_'extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F'.conf
>   
>     MToolBox.sh -i config_'extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F'.conf -m '-t 35'
> 
> Command exit status:
>   1
> 
> Command output:
>   ##### EXECUTING READ MAPPING WITH MAPEXOME...
>   
>   mapExome for sample extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F, files found: extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F.R1.fastq extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F.R2.fastq extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F.fastq
>   extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F.fastq is an empty unpaired fastq. File has been removed.
>   Mapping onto mtDNA...
>   /src/MToolBox/bin/gmap/bin/gsnap -D /src/gmapdb/ --gunzip -d chrRSRS -A sam --nofails --pairmax-dna=500 --query-unk-mismatch=1 --read-group-id=sample --read-group-name=sample --read-group-library=sample --read-group-platform=sample -n 1 -Q -O -t 35 extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F.R1.fastq extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F.R2.fastq > OUT_extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F/outmt.sam 2> OUT_extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F/logmt.txt
>   Extracting FASTQ from SAM...
>   Mapping onto complete human genome...single reads
>   Mapping onto complete human genome...pair reads
>   Reading Results...
>   Filtering reads...
>   Outfile saved on OUT_extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F/OUT.sam.
>   Done.
>   
>   Compression of fastq files from bam/sam input files...
>   Done.
>   
>   SAM files post-processing...
>   
>   ##### SORTING OUT.sam FILES WITH PICARDTOOLS...
>   
>   Success.
>   
>   Skip Indel Realigner...
>   Skipping Mark Duplicates...
>   
>   ##### ASSEMBLING MT GENOMES WITH ASSEMBLEMTGENOME...
>   
>   WARNING: values of tail < 5 are deprecated and will be replaced with 5
>   
>   
>   ##### GENERATING VCF OUTPUT...
>   
>   ##### PREDICTING HAPLOGROUPS AND ANNOTATING/PRIORITIZING VARIANTS...
>   
>   Haplogroup predictions based on RSRS Phylotree build 17
>   Your best results file is  mt_classification_best_results.csv
>   
>   Loading contig sequences from file extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F-contigs.fasta
>   Loaded 1 contig sequences
>   
>   Aligning Contigs to mtDNA reference genome...
>   
>   Heteroplasmy data file ('VCF_dict_tmp') not found. HF will not be reported in the output.
>   Parsing pathogenicity table...
>   Parsing variability data...
>   Parsing info about haplogroup-defining sites...
>   Parsing info about haplogroup assignments...
>   No annotation.csv found. Exit
> 
> Command error:
>   ##### SORTING OUT.sam FILES WITH PICARDTOOLS...
>   
>   [Thu Jan 26 17:54:04 GMT 2023] net.sf.picard.sam.SortSam INPUT=OUT.sam OUTPUT=OUT.sam.bam SORT_ORDER=coordinate TMP_DIR=[OUT_extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F/tmp]    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
>   [Thu Jan 26 17:54:04 GMT 2023] Executing as ?@eb9b63a9b3d8 on Linux 3.10.0-1160.80.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08; Picard version: 1.98(1547)
>   INFO	2023-01-26 17:54:04	SortSam	Finished reading inputs, merging and writing to output now.
>   [Thu Jan 26 17:54:04 GMT 2023] net.sf.picard.sam.SortSam done. Elapsed time: 0.00 minutes.
>   Runtime.totalMemory()=1045430272
>   Success.
>   
>   Skip Indel Realigner...
>   Skipping Mark Duplicates...
>   [Thu Jan 26 17:54:04 GMT 2023] net.sf.picard.sam.SamFormatConverter INPUT=OUT.sam.bam.marked.bam OUTPUT=OUT.sam.bam.marked.bam.marked.sam TMP_DIR=[OUT_extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F/tmp]    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
>   [Thu Jan 26 17:54:04 GMT 2023] Executing as ?@eb9b63a9b3d8 on Linux 3.10.0-1160.80.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08; Picard version: 1.98(1547)
>   [Thu Jan 26 17:54:04 GMT 2023] net.sf.picard.sam.SamFormatConverter done. Elapsed time: 0.00 minutes.
>   Runtime.totalMemory()=1045430272
>   
>   ##### ASSEMBLING MT GENOMES WITH ASSEMBLEMTGENOME...
>   
>   WARNING: values of tail < 5 are deprecated and will be replaced with 5
>   
>   [mpileup] 1 samples in 1 input files
>   <mpileup> Set max per-file depth to 8000
>   Traceback (most recent call last):
>     File "/src/MToolBox/MToolBox/assembleMTgenome.py", line 504, in <module>
>       if len(consensus_single) == 0:
>   TypeError: object of type 'NoneType' has no len()
>   
>   ##### GENERATING VCF OUTPUT...
>   Traceback (most recent call last):
>     File "/src/MToolBox/MToolBox/VCFoutput.py", line 36, in <module>
>       VCF_dict = ast.literal_eval(open('VCF_dict_tmp', 'r').read())
>   IOError: [Errno 2] No such file or directory: 'VCF_dict_tmp'
>   
>   ##### PREDICTING HAPLOGROUPS AND ANNOTATING/PRIORITIZING VARIANTS...
>   
>   Haplogroup predictions based on RSRS Phylotree build 17
>   Unable to compute haplogroup. ExitYour best results file is  mt_classification_best_results.csv
>   
>   Loading contig sequences from file extracted_mt_reads_normal_RLPRIGXR000011-N001-B01-F-contigs.fasta
>   Loaded 1 contig sequences
>   
>   Aligning Contigs to mtDNA reference genome...
>   
>   Heteroplasmy data file ('VCF_dict_tmp') not found. HF will not be reported in the output.
>   Parsing pathogenicity table...
>   Parsing variability data...
>   Parsing info about haplogroup-defining sites...
>   Parsing info about haplogroup assignments...
>   No annotation.csv found. Exit
> 
> Work dir:
>   /scratch/1d/becb0dc7057b308f6ef6ade5bc2d9f
> 
> Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by rhughwhite** [comment]
Having this error again, I will try with increased memory based on discussion here and in #102. Just noting here that this error is not causing the jobs to fail and so they are running indefinitely in these cases.
